import Head from "next/head";
import { FaSearch, FaUser, FaSignOutAlt, FaBuilding, FaPeopleArrows, FaScrewdriver} from "react-icons/fa";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
    const router = useRouter()
    let username = ""
    let password = ""
    let token = ""
    
    try{
        username = localStorage.getItem("username_stored")
        password = localStorage.getItem("username_stored")
        token = localStorage.getItem("access_token")
        console.log(token)
        console.log(username)
        console.log(password)
    }catch{}


    useEffect(() => {
        if(token == ""){
            router.push("/")
        }
    })

  return (
    <div>
      <Head>
        <title>Companies Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex justify-start overflow-y-hidden ">

        <div className=" h-screen px-4 pt-8 bg-cyan-600 flex justify-between flex-col w-60 "> {/* This is the side bar  */ }

            <div className="flex justify-center items-center">
                <FaUser className="text-white mr-3"/>
                <a href="#" className="text-white font-bold">My Account</a>
            </div>

            <div className="flex-row justify-center items-center">

                <div className="flex justify-center items-center mb-3">
                    <FaBuilding className="text-white mr-3"/>
                    <a href="#" className="text-white font-bold">Companies</a>
                </div>

                <div className="flex justify-center items-center mb-3">
                    <FaPeopleArrows className="text-white mr-3"/>
                    <a href="#" className="text-white font-bold">Employees</a>
                </div>

                <div className="flex justify-center items-center mb-3">
                    <FaScrewdriver className="text-white mr-3"/>
                    <a href="#" className="text-white font-bold">Settings</a>
                </div>

            </div>

            
                
            <a href="http://localhost:3000" className="text-white font-bold flex justify-center
            items-center mb-5 border-2 rounded-full p-2
            hover:text-cyan-600 hover:bg-white"
            >Sign Out
            </a>
        

        </div>

        <div className="flex-1 bg-gray-100 p-5 h-screen">

            <p className="font-bold mb-5"> <span className="text-cyan-600">Companies</span> Service</p>

            <div className="bg-white rounded-2xl items-center justify-start p-5 shadow-2xl flex flex-col h-[85vh] overflow-y-scroll">

                {/* <div className="flex flex-row justify-center items-center mb-5">
                    <div className=" flex justify-center items-center mr-9">
                        <p className="font-bold mr-3">Search by name </p>
                        <div className=" p-3 bg-gray-200 flex rounded-2xl items-center ">
                            <FaSearch className="text-gray-400 mr-2"/>
                            <input name="name" type="text" placeholder="ex. Novidea" className=" bg-gray-200 
                            outline-none"/>
                        </div>
                    </div>

                    <div className="flex justify-center items-center bg-gray-200 rounded-full p-3">
                        <p className="mr-3 font-bold"> &lt; |</p>
                        <p>1</p>
                        <p className="font-bold ml-3">| &gt; </p>
                    </div>

                </div>

                <div className="border-2 w-full border-gray-200 inline-block mb-2 rounded-2xl"></div> */}

                {/* Grid for the companies */}

            </div>

        </div>
      </main>
    </div>
  );
}
