import Head from "next/head";
import { useState } from "react";
import { FaRegEnvelope, FaLock } from "react-icons/fa";
import Router from "next/router";
import { useCookies } from "react-cookie";

const loginWithCRedentials = (
  username,
  password,
  setUser,
  setPass,
  setCookie
) => {
  const qs = require("querystring");
  const http = require("http");

  const options = {
    method: "POST",
    hostname: "localhost",
    port: "8543",
    path: "/realms/quarkus/protocol/openid-connect/token",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      "Content-Length": "0",
    },
  };

  const req = http.request(options, function (res) {
    const chunks = [];
    let status_code;

    res.on("data", function (chunk) {
      chunks.push(chunk);
    });

    res.on("end", function (response) {
      if (res.statusCode == 200) {
        const body = Buffer.concat(chunks);
        const response_body = JSON.parse(body.toString());
        console.log(response_body);
        console.log(response_body["access_token"]);

        localStorage.setItem("username_stored", username);
        localStorage.setItem("password_stored", password);
        localStorage.setItem("access_token", response_body["access_token"]);

        setCookie("Username", username, { path: "/" });
        setCookie("Password", password, { path: "/" });
        setCookie("Token_cookie", response_body["access_token"], { path: "/" });

        Router.push("/home");
      } else {
        setUser("");
        setPass("");
        alert("Invalid Username or password");
      }
    });
  });

  req.write(
    qs.stringify({
      client_id: "backend-service",
      client_secret: "secret",
      username: username,
      password: password,
      grant_type: "password",
    })
  );
  req.end();
};

export default function index() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [cookies, setCookie] = useCookies(["user"]);

  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2 bg-gray-200">
      <Head>
        <title>Companies Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <div className="bg-white rounded-2xl shadow-2xl flex w-2/3 max-w-4xl">
          <div className="w-3/5 p-5">
            <div className="text-left">
              <p className="font-bold">
                {" "}
                <span className="text-cyan-600">Companies</span> Service
              </p>
            </div>

            <div className="py-10">
              <h2 className="text-3xl font-bold text-cyan-600">
                Sign in to Account
              </h2>
            </div>

            <div className="border-2 w-10 border-cyan-600 inline-block mb-2 rounded-2xl"></div>

            <div className="flex flex-col items-center">
              <div className="bg-gray-200 w-66 p-3 flex items-center mb-3">
                <FaRegEnvelope className="text-gray-400 mr-3" />
                <input
                  onInput={(e) => setUsername(e.target.value)}
                  type="email"
                  required
                  value={username}
                  placeholder="Email"
                  className="bg-gray-200 outline-none text-sm"
                />
              </div>

              <div className="bg-gray-200 w-66 p-3 flex items-center mb-3">
                <FaLock className="text-gray-400 mr-3" />
                <input
                  onInput={(e) => setPassword(e.target.value)}
                  type="password"
                  value={password}
                  required
                  placeholder="Password"
                  className="bg-gray-200 outline-none text-sm"
                />
              </div>

              <a href="#" className="text-gray-400 text-sm text-left mb-5">
                Forgot my password
              </a>

              <button
                onClick={(e) =>
                  loginWithCRedentials(
                    username,
                    password,
                    setUsername,
                    setPassword,
                    setCookie
                  )
                }
                className="border-2 border-cyan-600 text-cyan-600 rounded-full py-2 px-10 inline-block
          hover:bg-cyan-600 hover:text-white"
              >
                {" "}
                Sign in{" "}
              </button>
            </div>
          </div>

          <div className="w-2/5 bg-cyan-600 rounded-tr-2xl rounded-br-2xl py-36 px-12">
            <p className="text-3xl font-bold mb-2 text-white">
              Sign up as User
            </p>

            <div className="border-2 w-10 border-white inline-block mb-2 rounded-2xl"></div>

            <p className="text-white mb-2">
              Create a user Account to manage mutliple companies information and
              their employees
            </p>

            <a
              href="#"
              className="border-2 border-white text-white rounded-full py-2 px-10 inline-block
          hover:bg-white hover:text-cyan-600"
            >
              {" "}
              Sign up{" "}
            </a>
          </div>
        </div>
      </main>
    </div>
  );
}
